### ISSUE TITLE
关于Associated Objects的疑问

### ISSUE THREAD

**Issue by yeziahehe** [ibireme/YYCategories#12]
在封装UIBarButtonItem的Category的时候，发现你使用了Associated Objects去进行了封装，因为你使用的时候必要时用一个block的property，我想问，下面的方式都能够实现同样的功能，Associated Objects的优点在哪儿？
<img width="892" alt="2016-01-06 9 58 41" src="https://cloud.githubusercontent.com/assets/8090437/12137337/9ae7904e-b48a-11e5-8982-d03320b1bfe6.png">

**Comment by ibireme** [comment]
没什么优势。。功能也不会有什么差异。
这块儿直接从 UIControl+YYAdd 里拷过来的代码，所以相关逻辑也带过来了。

**Comment by yeziahehe** [comment]
@ibireme 我想了很久，一直徘徊这里，其实只是两种实现方式。因为Associated Objects优势体现在要自定义属性的时候。
我的另外一个问题，再有自定义属性的时候，什么情况下选用继承，什么情况下选用Associated Objects去做Category呢？

**Comment by ibireme** [comment]
没必要的话就不要用 Associated Objects，写起来麻烦，性能又不高。

**Comment by yeziahehe** [comment]
性能不高指的是？是否有文档解释这个性能？

**Comment by ibireme** [comment]
没文档，但可以自己测一下。

**Comment by yeziahehe** [comment]
好的，感谢！
