### ISSUE TITLE
该类库与Masonry冲突

### ISSUE THREAD

**Issue by wzi90921** [ibireme/YYCategories#13]
Masonry 会定义该宏
If you want to use masonry without all those pesky 'mas_' prefixes. Add #define MAS_SHORTHAND to your prefix.pch before importing Masonry
# define MAS_SHORTHAND

如果引入YYCategories的话，省略了mas_的代码都会报错。。。。

**Comment by ibireme** [comment]
YYCategories 里面会给 UIView 添加 top、bottom、left、right、width、height 等属性，这些可能会和其它库产生冲突。

我在 Readme 写到了这个问题：https://github.com/ibireme/YYCategories#关于
