### ISSUE TITLE
@“123456” 检测包含 emoji 符号

### ISSUE THREAD

**Issue by shengdoushi** [ibireme/YYCategories#14]
测试环境模拟器 ios 9.2 (13C75), iPhone 6s Plus:

```
BOOL ok = [@"123456" containsEmoji];
```

竟然检测 ok 是 YES。

yy版本是：

pod 'YYCategories', '~> 0.9.3'

**Comment by ibireme** [comment]
这个方法将来会被删除掉。。

Emoji 应该是直接判断文本排版后的结果，而不应该根据字符串来判断，不然在某些地方还是会有问题。不同系统版本，不同显示框架 (UIKit/CoreText) 有时也会有不同的排版结果，所以这里还是把这个方法删掉吧。。
