### ISSUE TITLE
addActionBlock 中为何会中自动释放 target？

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYCategories#17]
代码没有问题，只是有个地方有点疑惑。以下是 UIGestureRecognizer+YYAdd 的源代码，我尝试注释了把 target 添加到数组的代码。按我的理解之所以加到数组是为了后续方便 remove，但是结果却是 target 出了这个作用域自动释放了，打印 gesture 实例发现 target 也是 nil 。奇怪，难道 `addTarget:action` 不会对 target 强制持有吗？求解惑。

``` objc
- (void)addActionBlock:(void (^)(id sender))block {
    _YYUIGestureRecognizerBlockTarget *target = [[_YYUIGestureRecognizerBlockTarget alloc] initWithBlock:block];
    [self addTarget:target action:@selector(invoke:)];
//    NSMutableArray *targets = [self _yy_allUIGestureRecognizerBlockTargets];
//    [targets addObject:target];
}
```

**Comment by ibireme** [comment]
这个要看看苹果的文档吧，如果是强引用的话，文档中大多会特别注明的（例如 NSTimer 里是这样注明的：@param target  The timer maintains a strong reference to this object until it (the timer) is invalidated.），没特殊说明的对象一般都不是强引用。

**Comment by KittenYang** [comment]
苹果在 UIGestureRecognizer 的文档里缺少对 target-action 的过多解释。不过在《OC 编程概念》的 [Target-Action](https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/Target-Action/Target-Action.html) 一节中，苹果有提到这么一句： `Control objects do not (and should not) retain their targets.`。按照惯例如果有特殊情况（比如 NSTimer ）会特别提醒，所以 UIGestureRecognizer 应该不会对 target 强引用。感谢回复。
