### ISSUE TITLE
UIControl+YYAdd

### ISSUE THREAD

**Issue by renlongyu** [ibireme/YYCategories#2]
- (void)removeAllBlocksForControlEvents:(UIControlEvents)controlEvents;
  UIControlEventAllEvents != UIControlEventTouchUpInside.
  添加的是UIControlEventTouchUpInside, 删除时用UIControlEventAllEvents, 方法里面if 判断的时候, 它俩是不相等的,所以就不会删除

**Comment by 312362115** [comment]
- (void)removeAllTargets
  删除全部targets的时候, 也会把所有的block targets也删掉. 并没有清除_yy_allUIControlBlockTargets中的target

**Comment by ibireme** [comment]
Fixed.
