### ISSUE TITLE
imageByInsetEdge:withColor:方法无法显示边框颜色

### ISSUE THREAD

**Issue by ColinHwang** [ibireme/YYCategories#21]
UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(100, 100, 200, 200)];
UIImage *image = [[UIImage imageNamed:@"1"] imageByInsetEdge:UIEdgeInsetsMake(0, 10, 0, 0) withColor:[UIColor redColor]];
[imageView setImage:image];
[self.view addSubview:imageView];

能看到图片被盖了, 但是是白色的, 并无红色啊。。。

**Comment by ibireme** [comment]
imageByInsetEdge 会按指定 insets 进行向内裁减。如果 insets 是负值，则表示向外扩张，这时候扩张出的那些像素就才会被颜色填充。

**Comment by ColinHwang** [comment]
原来如此，感谢回复。
