### ISSUE TITLE
imageWithPDF:方法有个小Bug

### ISSUE THREAD

**Issue by ColinHwang** [ibireme/YYCategories#22]
通过PDF文件路径获取:
`UIImage *image = [UIImage imageWithPDF:[[NSBundle mainBundle] pathForResource:@"4.pdf" ofType:@""]];`

会报错:
`<Error>: CFURLCreateDataAndPropertiesFromResource: failed with error code -15.`

Problem:
`pdf = CGPDFDocumentCreateWithURL((__bridge CFURLRef)[NSURL URLWithString:dataOrPath]);`
Fix:
`pdf = CGPDFDocumentCreateWithURL((__bridge CFURLRef)[NSURL fileURLWithPath:dataOrPath]);`

**Comment by ibireme** [comment]
Fixed
