### ISSUE TITLE
imageByRoundCornerRadius切圆形头像问题~

### ISSUE THREAD

**Issue by Ackerman64** [ibireme/YYCategories#24]
你好~ 如标题描述，用贝塞尔曲线对UIImage切成圆形，生成的图片边缘有明显的锯齿，或者说毛刺，显得比较粗糙。如果在UIImageView中直接用layer.cornerRadius则比较顺滑，但是会对fps产生影响。 不知道这个问题是否有解决办法？

**Comment by ibireme** [comment]
锯齿是指什么？能给段代码和截图说明一下吗？

**Comment by ibireme** [comment]
我猜，有可能你的图片和 ImageView 像素不对齐导致的。

**Comment by Ackerman64** [comment]
谢回复~ 的确有可能是像素不对齐导致的，回去改了下代码，发现还是存在此问题，但是相比起之前的情况是有较大的改善。如图，左边是直接设置imageView的layer.corneRadius，右边是切图后再设置imageView.image。（P.S.  imageView的大小是45pt的正方形）
![roundimage](https://cloud.githubusercontent.com/assets/5457040/16572725/61edd440-429e-11e6-9d2d-fa2059096ab0.jpg)

切圆形图的代码如下~，只是稍微改了下你写的扩展，贝塞尔曲线直接换成圆形：
` CGFloat minSize = MIN(PointPixelRound(self.size.width), PointPixelRound(self.size.height));
    （PointPixelRound是经你提醒新加的四舍五入像素对齐）

```
CGRect rect = CGRectMake(0, 0, minSize, minSize);
UIGraphicsBeginImageContextWithOptions(rect.size, NO, self.scale);
CGContextRef context = UIGraphicsGetCurrentContext();
CGContextScaleCTM(context, 1, -1);
CGContextTranslateCTM(context, 0, -rect.size.height);

UIBezierPath *path = [UIBezierPath bezierPathWithOvalInRect:rect];
[path closePath];

CGContextSaveGState(context);
[path addClip];
CGContextDrawImage(context, rect, self.CGImage);
CGContextRestoreGState(context);

if (borderColor && borderWidth < minSize / 2 && borderWidth > 0) {
    CGFloat strokeInset = (floor(borderWidth * self.scale) + 0.5) / self.scale;
    CGRect strokeRect = CGRectInset(rect, strokeInset, strokeInset);
    UIBezierPath *path = [UIBezierPath bezierPathWithOvalInRect:strokeRect];
    [path closePath];

    path.lineWidth = borderWidth;
    path.lineJoinStyle = kCGLineJoinRound;
    [borderColor setStroke];
    [path stroke];
}

UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return image;
```

`

可以用你的YYKitDemo的微博头像做下放大观看，应该也有类似的问题

**Comment by ibireme** [comment]
这是一个微博头像：http://tp3.sinaimg.cn/1662766362/180/5736567475/1

测试代码：

```
UIImage *img1 = [UIImage imageNamed:@"image_test"];
CGFloat cornerRadius = img1.size.width / 2;
UIImageView *v1 = [[UIImageView alloc] initWithImage:img1];
v1.clipsToBounds = YES;
v1.layer.cornerRadius = cornerRadius;

UIImage *img2 = [img1 imageByRoundCornerRadius:cornerRadius];
UIImageView *v2 = [[UIImageView alloc] initWithImage:img2];
```

<img width="246" alt="2016-07-06 12 36 37" src="https://cloud.githubusercontent.com/assets/839283/16592156/e1015e82-4311-11e6-98e4-24f2f4c69d79.png">
拿着放大镜看也是没问题的。

**Comment by Ackerman64** [comment]
测试了一下，UIImageView的大小跟着UIImage的大小走，是没问题的。

但是假如强行指定UIImageView的大小为比原图更小的尺寸时，会出现之前描述的情况。
以爱范儿的微博头像为例，http://tp1.sinaimg.cn/1642720480/180/40020887226/1，
指定pt为45*45  
测试代码：

```
    UIImage *img1 = [UIImage imageNamed:@"f"];
    CGFloat cornerRadius = img1.size.width / 2;
    UIImageView *v1 = [[UIImageView alloc] initWithImage:img1];
    v1.size = CGSizeMake(45, 45);
    v1.clipsToBounds = YES;
    v1.layer.cornerRadius = v1.width / 2;
    v1.origin = CGPointMake(60, 100);
    [self.view addSubview:v1];

    UIImage *img2 = [img1 imageByRoundCornerRadius:cornerRadius];
    UIImageView *v2 = [[UIImageView alloc] initWithImage:img2];
    v2.size = CGSizeMake(45, 45);
    v2.origin = CGPointMake(60, v1.bottom + 10);
    [self.view addSubview:v2];
```

<img width="45" alt="2" src="https://cloud.githubusercontent.com/assets/5457040/16608945/6d12bea0-4382-11e6-8915-b61c207d04d4.png">

**Comment by ibireme** [comment]
这就是上面说的图片和 ImageView 像素不对齐导致的啊。用 layer corner 时，相当于是先缩放在取圆形；而手动裁剪时，是相当于先取圆形再缩放，这时圆形边缘的像素就会受到影响了。

**Comment by Ackerman64** [comment]
明白！谢谢提点！

抱歉，重开了issue，有个问题想请教咨询下：

以上面“爱范儿”头像为例，其原图Image像素值是 180 \* 180。 而制定的UIImageView像素值是 90 \* 90（两倍屏）。从图形的直径来比较，刚好是缩小一半，这里的数值没产生像素不对齐。但是对于圆形边缘，该怎么去计算确定它是否产生了像素不对齐呢？

**Comment by ibireme** [comment]
对比 imageView 的在屏幕上所占像素（view.size \* screenScale），和 image 的像素 (image.size \* image.scale) 就行，这个与图片内容无关。

如果正好成整数比例，那内容会比较正常。如果恰好比整数多一点或少一点，那就容易出现 upscale downscale 时的毛刺感。

**Comment by Ackerman64** [comment]
好，麻烦了
