### ISSUE TITLE
是否调用里私有api,无法上线?

### ISSUE THREAD

**Issue by Nododo** [ibireme/YYCategories#5]
首先感谢你分享这么多好用的东西,万分感谢!
其次就是咨询下这些分类中是否用到了系统私有api,导致无法通过审核?
多谢!
再次感谢你的分享~

**Comment by ibireme** [comment]
没有用私有 API。这个项目里大部分代码都在我们的工程内使用了很久，所以审核应该没什么问题。

谨慎起见，可以尝试在小版本或没有上线压力的情况下试用，如有问题可以及时沟通。

**Comment by Nododo** [comment]
Thanks

**Comment by zhiqiangbai** [comment]
UIDevice (YYAdd)分类里面
@property (nonatomic, readonly) BOOL isPad;
property cannot have array or function type 'BOOl(0)'
这个属性怎么了??  Xcode 7.2 , iOS 9.2
麻烦指教一下,Thanks

**Comment by ibireme** [comment]
上面这个，可能是 Xcode 在编译时的问题。。
试试检查一下引入这个头文件的代码中，是否有其他错误（比如某个类缺少 @end），尝试 Clean 一下工程，清空缓存再编译看看。
