### ISSUE TITLE
使用体验 ：）

### ISSUE THREAD

**Issue by shenguanjiejie** [ibireme/YYCategories#7]
首先同为90年出生，好佩服作者。。。
今天用YYCategories，功能上面没的说给力好用，不过引入YYCategories后编译报错，还是我没见过的错误，查了半天也不知道怎么回事。后来仔细地找才发现是YYCategories中的方法名或者宏之类的与项目中的某些定义冲突了（因为项目比较老，所以还在用pch文件，我是直接把YYCategories放到pch文件里了）。总之就是觉得YYCategories的命名还是很容易导致冲突的，个人觉得把命名前面加上yy_前缀就不会有这些意外的事发生了，我能力平平，说的不对请忽略。

**Comment by ibireme** [comment]
Readme 最下面已经对这个情况说明了～
其实我觉得 Category 这种东西，每个人、每个团队都有自己的偏好吧。。

**Comment by shenguanjiejie** [comment]
哦哦 没看到 这个issue可以关闭了~
