### ISSUE TITLE
UIColor 可以加个 rgb int参数的不？

### ISSUE THREAD

**Issue by shengdoushi** [ibireme/YYCategories#9]
虽然可以通过 
- (UIColor *)colorWithRGB:(uint32_t)rgbValue;

但是加上这个某些时候更方便些： 
- (UIColor *)colorWithIntRed:(UInt8)red green:(UInt8)green blue:(UInt8)blue alpha:(UInt8)alpha;
- (UIColor *)colorWithIntRed:(UInt8)red green:(UInt8)green blue:(UInt8)blue;

可以直接使用  RGB(11, 134, 123) 这样的形式了，

**Comment by ibireme** [comment]
UIColor 本身就已经有 `+ (UIColor *)colorWithRed:(CGFloat)red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha;` 这个方法了，如果在加其他相似名字的方法，容易引起混淆。

另外，可能每个个人或团队都有自己的一套宏定义习惯吧，这个没必要加进来。
